extends:
  - "airbnb"
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "react-hooks"
root: true
rules:
  "@typescript-eslint/no-floating-promises":
    - "error"
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - argsIgnorePattern: _
      varsIgnorePattern: _
  arrow-body-style: "off"
  import/prefer-default-export: "off"
  no-console: "off"
  no-void: "off"
  prefer-destructuring: "off"
  prefer-template: "off"
  react/destructuring-assignment: "off"
  react/function-component-definition:
    - "error"
    - namedComponents: "function-declaration"
      unnamedComponents: "function-expression"
  react/no-unstable-nested-components:
    - "error"
    - allowAsProps: true
  react/prop-types: "off"
  react/react-in-jsx-scope: "off"
  react/require-default-props: "off"
  spaced-comment:
    - "error"
    - "always"
    - markers:
        - "/"
        - "**"
