bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: all
useTabs: false

overrides:
  - files: ["*.d.ts", "*.ts", "*.tsx"]
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
