name: "Deploy the app to Vercel"

env:
  REACT_APP_INFURA_API_KEY: "${{ secrets.REACT_APP_INFURA_API_KEY }}"
  REACT_APP_NODE_ENV: "${{ secrets.REACT_APP_NODE_ENV }}"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Pull Vercel Environment Information"
        run: "yarn vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes"

      - name: "Build Project Artifacts"
        run: "yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}"

      - name: "Add build summary"
        run: |
          echo "## Build results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Deploy Project Artifacts to Vercel"
        run: "yarn vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN}}"

      - name: "Add deploy summary"
        run: |
          echo "## Deploy results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
