name: "Deploy to IPFS"

env:
  REACT_APP_NODE_ENV: "${{ secrets.REACT_APP_NODE_ENV }}"

on: "workflow_dispatch"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Build the app"
        run: "yarn build"

      - name: "Add build summary"
        run: |
          echo "## Build results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Deploy the app to IPFS"
        id: "ipfs_action"
        uses: "aquiladev/ipfs-action@master"
        with:
          path: "./build"
          infuraProjectId: "${{ secrets.INFURA_IPFS_PROJECT_ID }}"
          infuraProjectSecret: "${{ secrets.INFURA_IPFS_API_KEY_SECRET }}"
          service: "infura"

      - name: "Add deploy summary"
        run: |
          echo "## Deploy results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed\n" >> $GITHUB_STEP_SUMMARY
          echo "IPFS hash: ${{ steps.ipfs_action.outputs.ipfs }}" >> $GITHUB_STEP_SUMMARY
